filter:
    excluded_paths:
        - vendor/*
        - Tests/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        redis: false
        docker: true
    dependencies:
        override:
            - ls -la
        before:
            - docker-compose up -d --remove-orphans --build
            - docker-compose exec -T php /usr/local/bin/php /usr/local/bin/composer install --no-suggest
            - docker-compose exec -T php /usr/local/bin/php /app/vendor/bin/phpunit --coverage-clover=./clover.xml
    nodes:
        analysis:
            tests:
                override:
                    -   command: ls -la
                        coverage:
                            file: clover.xml
                            format: clover
