language: php

php:
    - 7.3

before_install:
    - docker-compose up -d --remove-orphans --build
    - docker-compose exec -T php /usr/local/bin/php /usr/local/bin/composer install --no-suggest

script:
    - docker-compose exec -T php /usr/local/bin/php /app/vendor/bin/phpunit
