language: php
sudo: false

php:
    - 7.3

env:
    - SYMFONY_VERSION=4.0
    - SYMFONY_VERSION=4.*
    - SYMFONY_VERSION=4.* DEPENDENCIES=dev

services:
    - rdkafka

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - pecl install -f mongodb
    - composer install

script:
    - ./vendor/bin/phpunit
